version: 2.1
jobs:
    build_and_push:
        docker:
            - image: cimg/python:3.8
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: pip install -r requirements.txt
            - run:
                name: "Say Welcome"
                command: "echo Hello, This is SFS"
            - run:
                name: Install Dependencies
                command: pip install -r requirements.txt
            - run:
                name: Run tests 1
                command: |
                  pytest custlogin_test.py
            - run:
                name: Run tests 2
                command: |
                  pytest Agentlogintest.py
            - run:
                name: Debug Circle_SHA1
                command: echo "Circle_SHA1 is ${CIRCLE_SHA1}"
            - run:
                name: Docker build
                command: docker build -t $DOCKERHUB_USERNAME/sfs:${CIRCLE_SHA1} .  # Build a Docker image with a tag based on the commit SHA1
            - run:#sssa
                name: Authenticate with Docker Hub
                command: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin  # Logging in to Docker Hub
            - run:
                name: Push Docker Image to Docker Hub
                command: docker push $DOCKERHUB_USERNAME/sfs:${CIRCLE_SHA1}  # Push the Docker image to Docker Hub

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build_and_push:
                filters:
                    branches:
                        only: main
