version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: "Say Welcome"
          command: "echo Hello, This is SFS"
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests 1
          command: |
            pytest custlogin_test.py
      - run:
          name: Run tests 2
          command: |
            pytest Agentlogintest.py
      # Build Docker image upon successful tests
      # Start Docker daemon
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/sfs:latest .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/sfs:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main

