version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.8  # Example Python image that includes pip
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
