version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Update Pip
          command: pip install --upgrade pip

      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest testoverallcode.py

workflows:
  version: 2
  build:
    jobs:
      - build_and_push         #ssssss
