version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable  # Add the version field for the Docker image
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies  # Fix the syntax error here
          command: pip install -r requirements.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
