version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8  # Using a Python 3.8 Docker image
    steps:
      - checkout  # Check out the source code
      - setup_remote_docker:
          version: 19.03.13  # Setting a remote Docker environment.
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt  # Installing the dependencies through the requirements text.
      - run:
          name: Run tests
          command: pytest testoverallcode.py  # Run tests using pytestss
      
