version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest custlogin_test.py
